export const properties = [
  {
    category: "resale",
    ownerName: "Santech Engineering Pvt Ltd",
    projectName: "Century Breeze",
    builderName: "Century Real Estate Holdings Pvt Ltd",
    availableFrom: "2013",
    waterSupply: "borewell",
    amenities: {
      cyclingTrack: true,
      yogaDeck: true,
      outdoorGym: false,
      indoorGym: true,
      yogaRoom: false,
      spa: false,
      steamAndSauna: false,
      kidsPool: true,
      swimmingPool: true,
      aerobicsStudio: true,
      badmintonCourt: true,
      basketballCourt: true,
      volleyBallCourt: false,
      squashCourt: true,
      tennisCourt: true,
      cricketPitch: false,
      tableTennis: true,
      boxCricket: false,
      golf: false,
      multipurposeCourt: true,
      billiards: true,
      skatingRink: false,
      playArea: true,
      library: true,
      creche: true,
      danceStudio: false,
      videoGameRoom: false,
      adventureSports: false,
      oat: true,
      miniTheatre: false,
      functionHall: false,
      banquetHall: true,
      cafe: false,
      barbequePit: true,
      parks: true,
      seniorCitizenCorner: true,
      restHouse: false,
      natureTrail: false,
      terraceGarden: false,
      airConditioner: false,
      interCom: true,
      internet: true,
      petPark: true,
      gatedSecurity: true,
      cctv: true,
      fireAlarm: true,
      fireExtinguisher: true,
      waterSprinkler: true,
      entranceLobby: true,
      atm: false,
      businessCenter: true,
      superMarket: false,
      coWorkingSpace: true,
      lift: true,
      laundary: false,
      pharmacy: false,
      salon: false,
      groceryStore: false,
      houseKeeping: true,
      powerBackup: true,
      gasPipeline: false,
      garbageChute: false,
      rainwaterHarvesting: true,
      organicWasteConverter: false,
      solarHeater: false,
      solarLightning: false,
      sewageTreatmentPlant: true,
      visitorParking: true,
    },
    reraNo: "PRM/KA/RERA/1251/309/PR/170916/000324",
    unitName: "A-1304",
    propertyType: "apartment",
    configuration: "3BHK",
    plotConfiguration: null,
    sba: 1816,
    carpetArea: null,
    directionFacing: "east",
    floor: 13,
    parking: true,
    parkingType: "covered",
    noOfParking: 1,
    towerName: "A",
    phase: null,
    propertyLocation: "Jakkur",
    propertyAddress: "Jakkur Rd, Nehru Nagar, Bengaluru, Karnataka 560064",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    pincode: 560064,
    lat: 13.0960114761995,
    lng: 77.6009207452942,

    noOfBathrooms: 3,
    gatedCommunity: true,
    propertyAge: null,
    constructionStatus: "RTMI",
    tenancyStatus: "unavailable",
    siteInspectionStatus: "pending",
    bookingPricing: {
      expectedPrice1: 12500000,
    },
    registration: false,
    saleDeed: false,
    khata: false,
    ec: false,
    propertyTax: false,
    deposit: null,
    monthlyRental: null,
    maintenanceCharges2: null,
  },
  {
    category: "resale",
    ownerName: "Anil Gregory",
    projectName: "Century Ethos",
    builderName: "Century Real Estate Holdings Pvt Ltd",
    availableFrom: "2013",
    waterSupply: "borewell",
    amenities: {
      cyclingTrack: true,
      yogaDeck: true,
      outdoorGym: true,
      indoorGym: true,
      yogaRoom: true,
      spa: true,
      steamAndSauna: true,
      kidsPool: true,
      swimmingPool: true,
      aerobicsStudio: true,
      badmintonCourt: false,
      basketballCourt: true,
      volleyBallCourt: false,
      squashCourt: true,
      tennisCourt: true,
      cricketPitch: false,
      tableTennis: true,
      boxCricket: true,
      golf: true,
      multipurposeCourt: true,
      billiards: true,
      skatingRink: false,
      playArea: true,
      library: true,
      creche: true,
      danceStudio: false,
      videoGameRoom: true,
      adventureSports: false,
      oat: true,
      miniTheatre: true,
      functionHall: true,
      banquetHall: true,
      cafe: true,
      barbequePit: true,
      parks: true,
      seniorCitizenCorner: true,
      restHouse: true,
      natureTrail: false,
      terraceGarden: false,
      airConditioner: false,
      interCom: true,
      internet: true,
      petPark: true,
      gatedSecurity: true,
      cctv: true,
      fireAlarm: true,
      fireExtinguisher: true,
      waterSprinkler: true,
      entranceLobby: true,
      atm: true,
      businessCenter: true,
      superMarket: true,
      coWorkingSpace: true,
      lift: true,
      laundary: true,
      pharmacy: false,
      salon: true,
      groceryStore: true,
      houseKeeping: true,
      powerBackup: true,

      gasPipeline: true,
      garbageChute: true,
      rainwaterHarvesting: true,
      organicWasteConverter: false,
      solarHeater: false,
      solarLightning: false,
      carCharging: true,
      sewageTreatmentPlant: true,

      visitorParking: true,
    },
    reraNo: "PRM/KA/RERA/1251/309/PR/171014/000283",
    unitName: "901",
    propertyType: "apartment",
    configuration: "3BHK",
    plotConfiguration: null,
    sba: 2930,
    carpetArea: null,
    directionFacing: "west",
    floor: 9,
    parking: true,
    parkingType: "covered",
    noOfParking: 2,
    towerName: "A",
    phase: null,
    propertyLocation: "Hebbal",
    propertyAddress:
      "Bellary Rd, opposite Sahakaranagar, Kashi Nagar, Byatarayanapura, Bengaluru, Karnataka 560092",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    pincode: 560092,
    lat: 13.0633483898987,
    lng: 77.5950281309647,

    noOfBathrooms: 3,
    gatedCommunity: true,
    propertyAge: null,
    constructionStatus: "RTMI",
    siteInspectionStatus: "pending",
    bookingPricing: {
      expectedPrice1: 31500000,
    },
    registration: false,
    saleDeed: false,
    khata: false,
    ec: false,
    propertyTax: false,
    deposit: null,
    monthlyRental: null,
    maintenanceCharges2: null,
  },
  {
    category: "resale",
    ownerName: "R Sashidhar",
    projectName: "Century Ethos",
    builderName: "Century Real Estate Holdings Pvt Ltd",
    availableFrom: "2013",
    waterSupply: "borewell",
    amenities: {
      cyclingTrack: true,
      yogaDeck: true,
      outdoorGym: true,
      indoorGym: true,
      yogaRoom: true,
      spa: true,
      steamAndSauna: true,
      kidsPool: true,
      swimmingPool: true,
      aerobicsStudio: true,
      badmintonCourt: false,
      basketballCourt: true,
      volleyBallCourt: false,
      squashCourt: true,
      tennisCourt: true,
      cricketPitch: false,
      tableTennis: true,
      boxCricket: true,
      golf: true,
      multipurposeCourt: true,
      billiards: true,
      skatingRink: false,
      playArea: true,
      library: true,
      creche: true,
      danceStudio: false,
      videoGameRoom: true,
      adventureSports: false,
      oat: true,
      miniTheatre: true,
      functionHall: true,
      banquetHall: true,
      cafe: true,
      barbequePit: true,
      parks: true,
      seniorCitizenCorner: true,
      restHouse: true,
      natureTrail: false,
      terraceGarden: false,
      airConditioner: false,
      interCom: true,
      internet: true,
      petPark: true,
      gatedSecurity: true,
      cctv: true,
      fireAlarm: true,
      fireExtinguisher: true,
      waterSprinkler: true,
      entranceLobby: true,
      atm: true,
      businessCenter: true,
      superMarket: true,
      coWorkingSpace: true,
      lift: true,
      laundary: true,
      pharmacy: false,
      salon: true,
      groceryStore: true,
      houseKeeping: true,
      powerBackup: true,

      gasPipeline: true,
      garbageChute: true,
      rainwaterHarvesting: true,
      organicWasteConverter: false,
      solarHeater: false,
      solarLightning: false,
      carCharging: true,
      sewageTreatmentPlant: true,

      visitorParking: true,
    },
    reraNo: "PRM/KA/RERA/1251/309/PR/171014/000283",
    unitName: "102",
    propertyType: "apartment",
    configuration: "3BHK",
    sba: 3125,
    directionFacing: "north",
    floor: 1,
    parking: true,
    parkingType: "covered",
    noOfParking: 2,
    towerName: "A",
    propertyLocation: "Hebbal",
    propertyAddress:
      "Bellary Rd, opposite Sahakaranagar, Kashi Nagar, Byatarayanapura, Bengaluru, Karnataka 560092",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    pincode: 560092,
    lat: 13.0633483898987,
    lng: 77.5950281309647,
    noOfBathrooms: 3,
    gatedCommunity: true,
    constructionStatus: "RTMI",
    bookingPricing: {
      expectedPrice1: 33000000,
    },
    registration: false,
    saleDeed: false,
    khata: false,
    ec: false,
    propertyTax: false,
  },
  {
    category: "resale",
    ownerName: "Balasubramanyan Janaki Raman",
    projectName: "Century Horizon",
    builderName: "Century Real Estate Holdings Pvt Ltd",
    availableFrom: "2019",
    waterSupply: "borewell",
    amenities: {
      cyclingTrack: true,
      yogaDeck: true,
      outdoorGym: false,
      indoorGym: true,
      yogaRoom: false,
      spa: true,
      steamAndSauna: true,
      kidsPool: true,
      swimmingPool: true,
      aerobicsStudio: true,
      badmintonCourt: true,
      basketballCourt: true,
      volleyBallCourt: false,
      squashCourt: false,
      tennisCourt: true,
      cricketPitch: false,
      tableTennis: true,
      boxCricket: false,
      golf: false,
      multipurposeCourt: false,
      billiards: true,
      skatingRink: false,
      playArea: true,
      library: false,
      creche: false,
      danceStudio: false,
      videoGameRoom: false,
      adventureSports: false,
      oat: true,
      miniTheatre: false,
      functionHall: false,
      banquetHall: true,
      cafe: false,
      barbequePit: true,
      parks: true,
      seniorCitizenCorner: true,
      restHouse: false,
      natureTrail: false,
      terraceGarden: false,
      airConditioner: false,
      interCom: true,
      internet: true,
      petPark: true,
      gatedSecurity: true,
      cctv: true,
      fireAlarm: true,
      fireExtinguisher: true,
      waterSprinkler: true,
      entranceLobby: true,
      atm: false,
      businessCenter: true,
      superMarket: false,
      coWorkingSpace: false,
      lift: true,
      laundary: false,
      pharmacy: false,
      salon: false,
      groceryStore: false,
      houseKeeping: true,
      powerBackup: true,

      gasPipeline: false,
      garbageChute: false,
      rainwaterHarvesting: true,
      organicWasteConverter: false,
      solarHeater: false,
      solarLightning: false,

      sewageTreatmentPlant: true,

      visitorParking: true,
    },
    reraNo: "PRM/KA/RERA/1251/309/PR/191107/002988",
    unitName: "615",
    propertyType: "apartment",
    configuration: "2BHK",
    sba: 1119,
    directionFacing: "north",
    floor: 6,
    parking: true,
    parkingType: "covered",
    noOfParking: 1,
    propertyLocation: "Jakkur",
    propertyAddress: "Yashoda Nagar, Yelahanka, Bengaluru, Karnataka 560065",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    pincode: 560065,
    lat: 13.077060986727,
    lng: 77.5924583483184,
    noOfBathrooms: 2,
    gatedCommunity: true,
    constructionStatus: "nearing-completion",
    bookingPricing: {
      expectedPrice1: 10200000,
    },
    registration: false,
    saleDeed: false,
    khata: false,
    ec: false,
    propertyTax: false,
  },
  {
    category: "resale",
    ownerName: "Preethi Sudrashan",
    projectName: "Century Saras",
    builderName: "Century Real Estate Holdings Pvt Ltd",
    availableFrom: "2012",
    waterSupply: "borewell",
    amenities: {
      cyclingTrack: true,
      yogaDeck: true,
      outdoorGym: false,
      indoorGym: true,
      yogaRoom: false,
      spa: false,
      steamAndSauna: false,
      kidsPool: true,
      swimmingPool: true,
      aerobicsStudio: true,
      badmintonCourt: true,
      basketballCourt: true,
      volleyBallCourt: false,
      squashCourt: false,
      tennisCourt: false,
      cricketPitch: false,
      tableTennis: true,
      boxCricket: false,
      golf: false,
      multipurposeCourt: false,
      billiards: true,
      skatingRink: false,
      playArea: true,
      library: false,
      creche: false,
      danceStudio: false,
      videoGameRoom: false,
      adventureSports: false,
      oat: true,
      miniTheatre: false,
      functionHall: false,
      banquetHall: true,
      cafe: false,
      barbequePit: true,
      parks: true,
      seniorCitizenCorner: true,
      restHouse: false,
      natureTrail: false,
      terraceGarden: false,
      airConditioner: false,
      interCom: true,
      internet: true,
      petPark: true,
      gatedSecurity: true,
      cctv: true,
      fireAlarm: true,
      fireExtinguisher: true,
      waterSprinkler: false,
      entranceLobby: true,
      atm: false,
      businessCenter: true,
      superMarket: false,
      coWorkingSpace: false,
      lift: true,
      laundary: false,
      pharmacy: false,
      salon: false,
      groceryStore: false,
      houseKeeping: true,
      powerBackup: true,

      gasPipeline: false,
      garbageChute: false,
      rainwaterHarvesting: true,
      organicWasteConverter: false,
      solarHeater: false,
      solarLightning: false,

      sewageTreatmentPlant: true,

      visitorParking: true,
    },
    unitName: "103",
    propertyType: "apartment",
    configuration: "3BHK",
    sba: 1676,
    directionFacing: "west",
    floor: 1,
    parking: true,
    parkingType: "covered",
    noOfParking: 1,
    towerName: "A",
    propertyLocation: "Yelahanka",
    propertyAddress:
      "Anantapura Rd, Yelahanka New Town, Bengaluru, Karnataka 560064",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    pincode: 560064,
    lat: 13.1119660522076,
    lng: 77.5708423612199,
    gatedCommunity: true,
    constructionStatus: "RTMI",
    bookingPricing: {
      expectedPrice1: 8500000,
    },
    registration: true,
    saleDeed: true,
    khata: true,
    ec: true,
    propertyTax: false,
  },
  {
    category: "resale",
    ownerName: "Namrata Ghatage",
    projectName: "Century Eden I",
    builderName: "Century Real Estate Holdings Pvt Ltd",
    availableFrom: "2013",
    waterSupply: "borewell",
    amenities: {
      cyclingTrack: true,
      yogaDeck: true,
      outdoorGym: true,
      indoorGym: true,
      yogaRoom: false,
      spa: true,
      steamAndSauna: false,
      kidsPool: true,
      swimmingPool: true,
      aerobicsStudio: true,
      badmintonCourt: true,
      basketballCourt: true,
      volleyBallCourt: true,
      squashCourt: false,
      tennisCourt: true,
      cricketPitch: true,
      tableTennis: true,
      boxCricket: false,
      golf: false,
      multipurposeCourt: false,
      billiards: true,
      skatingRink: false,
      playArea: true,
      library: false,
      creche: false,
      danceStudio: false,
      videoGameRoom: false,
      adventureSports: false,
      oat: true,
      miniTheatre: false,
      functionHall: false,
      banquetHall: true,
      cafe: false,
      barbequePit: true,
      parks: true,
      seniorCitizenCorner: true,
      restHouse: false,
      natureTrail: true,
      terraceGarden: false,
      airConditioner: false,
      interCom: true,
      internet: true,
      petPark: true,
      gatedSecurity: true,
      cctv: true,
      fireAlarm: false,
      fireExtinguisher: true,
      waterSprinkler: false,
      entranceLobby: false,
      atm: false,
      businessCenter: false,
      superMarket: false,
      coWorkingSpace: false,
      lift: false,
      laundary: false,
      pharmacy: false,
      salon: false,
      groceryStore: true,
      houseKeeping: true,
      powerBackup: true,

      gasPipeline: false,
      garbageChute: false,
      rainwaterHarvesting: true,
      organicWasteConverter: false,
      solarHeater: false,
      solarLightning: false,

      sewageTreatmentPlant: true,

      visitorParking: true,
    },
    unitName: "445",
    propertyType: "plot",
    configuration: "plot",
    plotConfiguration: "40x60",
    carpetArea: 2400,
    directionFacing: "east",
    propertyLocation: "Doddaballapura Road",
    propertyAddress: "SH 9, Bisuvanahalli, Karnataka 561203",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    pincode: 561203,
    lat: 13.2347084909343,
    lng: 77.5501255597558,

    gatedCommunity: true,

    constructionStatus: "RTMI",
    bookingPricing: {
      expectedPrice1: 9800000,
    },
    registration: true,
    saleDeed: true,
    khata: true,
    ec: true,
    propertyTax: false,
  },
  {
    category: "resale",
    ownerName: "Nitish Mathew Panachayil",
    projectName: "Century Eden I",
    builderName: "Century Real Estate Holdings Pvt Ltd",
    availableFrom: "2013",
    waterSupply: "borewell",
    amenities: {
      cyclingTrack: true,
      yogaDeck: true,
      outdoorGym: true,
      indoorGym: true,
      yogaRoom: false,
      spa: true,
      steamAndSauna: false,
      kidsPool: true,
      swimmingPool: true,
      aerobicsStudio: true,
      badmintonCourt: true,
      basketballCourt: true,
      volleyBallCourt: true,
      squashCourt: false,
      tennisCourt: true,
      cricketPitch: true,
      tableTennis: true,
      boxCricket: false,
      golf: false,
      multipurposeCourt: false,
      billiards: true,
      skatingRink: false,
      playArea: true,
      library: false,
      creche: false,
      danceStudio: false,
      videoGameRoom: false,
      adventureSports: false,
      oat: true,
      miniTheatre: false,
      functionHall: false,
      banquetHall: true,
      cafe: false,
      barbequePit: true,
      parks: true,
      seniorCitizenCorner: true,
      restHouse: false,
      natureTrail: true,
      terraceGarden: false,
      airConditioner: false,
      interCom: true,
      internet: true,
      petPark: true,
      gatedSecurity: true,
      cctv: true,
      fireAlarm: false,
      fireExtinguisher: true,
      waterSprinkler: false,
      entranceLobby: false,
      atm: false,
      businessCenter: false,
      superMarket: false,
      coWorkingSpace: false,
      lift: false,
      laundary: false,
      pharmacy: false,
      salon: false,
      groceryStore: true,
      houseKeeping: true,
      powerBackup: true,

      gasPipeline: false,
      garbageChute: false,
      rainwaterHarvesting: true,
      organicWasteConverter: false,
      solarHeater: false,
      solarLightning: false,

      sewageTreatmentPlant: true,

      visitorParking: true,
    },
    unitName: "382",
    propertyType: "plot",
    configuration: "plot",
    plotConfiguration: "40x60",
    carpetArea: 2400,
    directionFacing: "east",
    propertyLocation: "Doddaballapura Road",
    propertyAddress: "SH 9, Bisuvanahalli, Karnataka 561203",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    pincode: 561203,
    lat: 13.2347084909343,
    lng: 77.5501255597558,

    gatedCommunity: true,

    constructionStatus: "RTMI",
    bookingPricing: {
      expectedPrice1: 9800000,
    },
    registration: true,
    saleDeed: true,
    khata: true,
    ec: true,
    propertyTax: false,
  },
  {
    category: "resale",
    ownerName: "Shridhar Kamath",
    projectName: "Century Eden I",
    builderName: "Century Real Estate Holdings Pvt Ltd",
    availableFrom: "2013",
    waterSupply: "borewell",
    amenities: {
      cyclingTrack: true,
      yogaDeck: true,
      outdoorGym: true,
      indoorGym: true,
      yogaRoom: false,
      spa: true,
      steamAndSauna: false,
      kidsPool: true,
      swimmingPool: true,
      aerobicsStudio: true,
      badmintonCourt: true,
      basketballCourt: true,
      volleyBallCourt: true,
      squashCourt: false,
      tennisCourt: true,
      cricketPitch: true,
      tableTennis: true,
      boxCricket: false,
      golf: false,
      multipurposeCourt: false,
      billiards: true,
      skatingRink: false,
      playArea: true,
      library: false,
      creche: false,
      danceStudio: false,
      videoGameRoom: false,
      adventureSports: false,
      oat: true,
      miniTheatre: false,
      functionHall: false,
      banquetHall: true,
      cafe: false,
      barbequePit: true,
      parks: true,
      seniorCitizenCorner: true,
      restHouse: false,
      natureTrail: true,
      terraceGarden: false,
      airConditioner: false,
      interCom: true,
      internet: true,
      petPark: true,
      gatedSecurity: true,
      cctv: true,
      fireAlarm: false,
      fireExtinguisher: true,
      waterSprinkler: false,
      entranceLobby: false,
      atm: false,
      businessCenter: false,
      superMarket: false,
      coWorkingSpace: false,
      lift: false,
      laundary: false,
      pharmacy: false,
      salon: false,
      groceryStore: true,
      houseKeeping: true,
      powerBackup: true,

      gasPipeline: false,
      garbageChute: false,
      rainwaterHarvesting: true,
      organicWasteConverter: false,
      solarHeater: false,
      solarLightning: false,

      sewageTreatmentPlant: true,

      visitorParking: true,
    },
    unitName: "99",
    propertyType: "plot",
    configuration: "plot",
    plotConfiguration: "30x40",
    carpetArea: 1200,
    directionFacing: "east",
    propertyLocation: "Off-IVC road",
    propertyAddress: "SH 9, Bisuvanahalli, Karnataka 561203",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    pincode: 561203,
    lat: 13.2347084909343,
    lng: 77.5501255597558,

    gatedCommunity: true,

    constructionStatus: "RTMI",
    bookingPricing: {
      expectedPrice1: 4750000,
    },
    registration: false,
    saleDeed: false,
    khata: false,
    ec: false,
    propertyTax: false,
  },
  {
    category: "resale",
    ownerName: "Ranganatha Hv",
    projectName: "Century Eden II",
    builderName: "Century Real Estate Holdings Pvt Ltd",
    availableFrom: "2019",
    waterSupply: "borewell",
    amenities: {
      cyclingTrack: true,
      yogaDeck: true,
      outdoorGym: true,
      indoorGym: true,
      yogaRoom: false,
      spa: true,
      steamAndSauna: false,
      kidsPool: true,
      swimmingPool: true,
      aerobicsStudio: true,
      badmintonCourt: true,
      basketballCourt: true,
      volleyBallCourt: true,
      squashCourt: false,
      tennisCourt: true,
      cricketPitch: true,
      tableTennis: true,
      boxCricket: false,
      golf: false,
      multipurposeCourt: false,
      billiards: true,
      skatingRink: false,
      playArea: true,
      library: false,
      creche: false,
      danceStudio: false,
      videoGameRoom: false,
      adventureSports: false,
      oat: true,
      miniTheatre: false,
      functionHall: false,
      banquetHall: true,
      cafe: false,
      barbequePit: true,
      parks: true,
      seniorCitizenCorner: true,
      restHouse: false,
      natureTrail: true,
      terraceGarden: false,
      airConditioner: false,
      interCom: true,
      internet: true,
      petPark: true,
      gatedSecurity: true,
      cctv: true,
      fireAlarm: false,
      fireExtinguisher: true,
      waterSprinkler: false,
      entranceLobby: false,
      atm: false,
      businessCenter: false,
      superMarket: false,
      coWorkingSpace: false,
      lift: false,
      laundary: false,
      pharmacy: false,
      salon: false,
      groceryStore: true,
      houseKeeping: true,
      powerBackup: true,

      gasPipeline: false,
      garbageChute: false,
      rainwaterHarvesting: true,
      organicWasteConverter: false,
      solarHeater: false,
      solarLightning: false,

      sewageTreatmentPlant: true,

      visitorParking: true,
    },
    reraNo: "PRM/KA/RERA/1250/301/PR/200323/003366",
    unitName: "31",
    propertyType: "plot",
    configuration: "plot",
    plotConfiguration: "30x40",
    carpetArea: 1200,
    directionFacing: "east",
    propertyLocation: "Dodabalapur",
    propertyAddress: "SH 9, Bisuvanahalli, Karnataka 561203",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    pincode: 561203,
    lat: 13.2347084909343,
    lng: 77.5501255597558,

    gatedCommunity: true,

    constructionStatus: "RTMI",
    bookingPricing: {
      expectedPrice1: 5500000,
    },
    registration: false,
    saleDeed: false,
    khata: false,
    ec: false,
    propertyTax: false,
  },
  {
    category: "resale",
    ownerName: "Ranganatha Hv",
    projectName: "Century Eden II",
    builderName: "Century Real Estate Holdings Pvt Ltd",
    availableFrom: "2019",
    waterSupply: "borewell",
    amenities: {
      cyclingTrack: true,
      yogaDeck: true,
      outdoorGym: true,
      indoorGym: true,
      yogaRoom: false,
      spa: true,
      steamAndSauna: false,
      kidsPool: true,
      swimmingPool: true,
      aerobicsStudio: true,
      badmintonCourt: true,
      basketballCourt: true,
      volleyBallCourt: true,
      squashCourt: false,
      tennisCourt: true,
      cricketPitch: true,
      tableTennis: true,
      boxCricket: false,
      golf: false,
      multipurposeCourt: false,
      billiards: true,
      skatingRink: false,
      playArea: true,
      library: false,
      creche: false,
      danceStudio: false,
      videoGameRoom: false,
      adventureSports: false,
      oat: true,
      miniTheatre: false,
      functionHall: false,
      banquetHall: true,
      cafe: false,
      barbequePit: true,
      parks: true,
      seniorCitizenCorner: true,
      restHouse: false,
      natureTrail: true,
      terraceGarden: false,
      airConditioner: false,
      interCom: true,
      internet: true,
      petPark: true,
      gatedSecurity: true,
      cctv: true,
      fireAlarm: false,
      fireExtinguisher: true,
      waterSprinkler: false,
      entranceLobby: false,
      atm: false,
      businessCenter: false,
      superMarket: false,
      coWorkingSpace: false,
      lift: false,
      laundary: false,
      pharmacy: false,
      salon: false,
      groceryStore: true,
      houseKeeping: true,
      powerBackup: true,

      gasPipeline: false,
      garbageChute: false,
      rainwaterHarvesting: true,
      organicWasteConverter: false,
      solarHeater: false,
      solarLightning: false,

      sewageTreatmentPlant: true,

      visitorParking: true,
    },
    reraNo: "PRM/KA/RERA/1250/301/PR/200323/003366",
    unitName: "30",
    propertyType: "plot",
    configuration: "plot",
    plotConfiguration: "30x40",
    carpetArea: 1200,
    directionFacing: "east",
    propertyLocation: "Dodabalapur",
    propertyAddress: "SH 9, Bisuvanahalli, Karnataka 561203",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    pincode: 561203,
    lat: 13.2347084909343,
    lng: 77.5501255597558,

    gatedCommunity: true,

    constructionStatus: "RTMI",
    bookingPricing: {
      expectedPrice1: 5500000,
    },
    registration: false,
    saleDeed: false,
    khata: false,
    ec: false,
    propertyTax: false,
  },
  {
    category: "resale",
    ownerName: "Rama Ravikanth Vijapurapu & Ms. Divya Tamvada",
    projectName: "Century Greens I",
    builderName: "Century Real Estate Holdings Pvt Ltd",
    availableFrom: "2018",
    waterSupply: "borewell",
    amenities: {
      cyclingTrack: true,
      yogaDeck: true,
      outdoorGym: false,
      indoorGym: true,
      yogaRoom: false,
      spa: true,
      steamAndSauna: true,
      kidsPool: true,
      swimmingPool: true,
      aerobicsStudio: true,
      badmintonCourt: true,
      basketballCourt: true,
      volleyBallCourt: false,
      squashCourt: false,
      tennisCourt: true,
      cricketPitch: false,
      tableTennis: true,
      boxCricket: false,
      golf: false,
      multipurposeCourt: false,
      billiards: true,
      skatingRink: false,
      playArea: true,
      library: false,
      creche: false,
      danceStudio: false,
      videoGameRoom: false,
      adventureSports: false,
      oat: true,
      miniTheatre: false,
      functionHall: false,
      banquetHall: true,
      cafe: false,
      barbequePit: true,
      parks: true,
      seniorCitizenCorner: true,
      restHouse: false,
      natureTrail: true,
      terraceGarden: false,
      airConditioner: false,
      interCom: true,
      internet: true,
      petPark: true,
      gatedSecurity: true,
      cctv: true,
      fireAlarm: false,
      fireExtinguisher: true,
      waterSprinkler: false,
      entranceLobby: false,
      atm: false,
      businessCenter: false,
      superMarket: true,
      coWorkingSpace: false,
      lift: false,
      laundary: false,
      pharmacy: false,
      salon: false,
      groceryStore: true,
      houseKeeping: true,
      powerBackup: true,

      gasPipeline: false,
      garbageChute: false,
      rainwaterHarvesting: true,
      organicWasteConverter: false,
      solarHeater: false,
      solarLightning: false,

      sewageTreatmentPlant: true,

      visitorParking: true,
    },
    reraNo: "PRM/KA/RERA/1250/303/PR/180905/001983",
    unitName: "337",
    propertyType: "plot",
    configuration: "plot",
    plotConfiguration: "Odd",
    carpetArea: 1878,
    directionFacing: "west",
    propertyLocation: "Devanahalli",
    propertyAddress:
      "SY No. 94, Next to cambridge institute of technology, Kundana, Devanahalli, Bengaluru, Karnataka 562110",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    pincode: 562110,
    lat: 13.2489449600997,
    lng: 77.613665445905,

    gatedCommunity: true,

    constructionStatus: "RTMI",
    bookingPricing: {
      expectedPrice1: 7500000,
    },
    registration: true,
    saleDeed: true,
    khata: true,
    ec: true,
    propertyTax: false,
  },
  {
    category: "resale",
    ownerName: "Guru Prakash V K ",
    projectName: "Century Greens I",
    builderName: "Century Real Estate Holdings Pvt Ltd",
    availableFrom: "2018",
    waterSupply: "borewell",
    amenities: {
      cyclingTrack: true,
      yogaDeck: true,
      outdoorGym: false,
      indoorGym: true,
      yogaRoom: false,
      spa: true,
      steamAndSauna: true,
      kidsPool: true,
      swimmingPool: true,
      aerobicsStudio: true,
      badmintonCourt: true,
      basketballCourt: true,
      volleyBallCourt: false,
      squashCourt: false,
      tennisCourt: true,
      cricketPitch: false,
      tableTennis: true,
      boxCricket: false,
      golf: false,
      multipurposeCourt: false,
      billiards: true,
      skatingRink: false,
      playArea: true,
      library: false,
      creche: false,
      danceStudio: false,
      videoGameRoom: false,
      adventureSports: false,
      oat: true,
      miniTheatre: false,
      functionHall: false,
      banquetHall: true,
      cafe: false,
      barbequePit: true,
      parks: true,
      seniorCitizenCorner: true,
      restHouse: false,
      natureTrail: true,
      terraceGarden: false,
      airConditioner: false,
      interCom: true,
      internet: true,
      petPark: true,
      gatedSecurity: true,
      cctv: true,
      fireAlarm: false,
      fireExtinguisher: true,
      waterSprinkler: false,
      entranceLobby: false,
      atm: false,
      businessCenter: false,
      superMarket: true,
      coWorkingSpace: false,
      lift: false,
      laundary: false,
      pharmacy: false,
      salon: false,
      groceryStore: true,
      houseKeeping: true,
      powerBackup: true,

      gasPipeline: false,
      garbageChute: false,
      rainwaterHarvesting: true,
      organicWasteConverter: false,
      solarHeater: false,
      solarLightning: false,

      sewageTreatmentPlant: true,

      visitorParking: true,
    },
    reraNo: "PRM/KA/RERA/1250/303/PR/180905/001983",
    unitName: "263",
    propertyType: "plot",
    configuration: "plot",
    plotConfiguration: "30x50",
    carpetArea: 1499,
    directionFacing: "east",
    propertyLocation: "off-IVC road",
    propertyAddress:
      "SY No. 94, Next to cambridge institute of technology, Kundana, Devanahalli, Bengaluru, Karnataka 562110",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    pincode: 562110,
    lat: 13.2489449600997,
    lng: 77.613665445905,

    gatedCommunity: true,

    constructionStatus: "RTMI",
    bookingPricing: {
      expectedPrice1: 6500000,
    },
    registration: true,
    saleDeed: true,
    khata: true,
    ec: true,
    propertyTax: false,
  },
  {
    category: "resale",
    ownerName: "Rajat Mathur",
    projectName: "Century Sports village",
    builderName: "Century Real Estate Holdings Pvt Ltd",
    availableFrom: "2014",
    waterSupply: "borewell",
    amenities: {
      cyclingTrack: true,
      yogaDeck: true,
      outdoorGym: true,
      indoorGym: true,
      yogaRoom: true,
      spa: true,
      steamAndSauna: false,
      kidsPool: true,
      swimmingPool: true,
      aerobicsStudio: true,
      badmintonCourt: true,
      basketballCourt: true,
      volleyBallCourt: true,
      squashCourt: false,
      tennisCourt: true,
      cricketPitch: true,
      tableTennis: true,
      boxCricket: false,
      golf: false,
      multipurposeCourt: false,
      billiards: true,
      skatingRink: false,
      playArea: true,
      library: false,
      creche: false,
      danceStudio: false,
      videoGameRoom: false,
      adventureSports: true,
      oat: true,
      miniTheatre: false,
      functionHall: false,
      banquetHall: true,
      cafe: false,
      barbequePit: true,
      parks: true,
      seniorCitizenCorner: true,
      restHouse: false,
      natureTrail: true,
      terraceGarden: false,
      airConditioner: false,
      interCom: true,
      internet: true,
      petPark: true,
      gatedSecurity: true,
      cctv: true,
      fireAlarm: false,
      fireExtinguisher: true,
      waterSprinkler: false,
      entranceLobby: false,
      atm: false,
      businessCenter: false,
      superMarket: false,
      coWorkingSpace: false,
      lift: false,
      laundary: false,
      pharmacy: false,
      salon: false,
      groceryStore: false,
      houseKeeping: true,
      powerBackup: true,

      gasPipeline: false,
      garbageChute: false,
      rainwaterHarvesting: true,
      organicWasteConverter: false,
      solarHeater: false,
      solarLightning: false,

      sewageTreatmentPlant: true,

      visitorParking: true,
    },
    reraNo: "PRM/KA/RERA/1250/303/PR/170918/000844",
    unitName: "696",
    propertyType: "plot",
    configuration: "plot",
    plotConfiguration: "40x60",
    carpetArea: 2400,
    directionFacing: "east",
    propertyLocation: "IVC",
    propertyAddress: "IVC Rd, Devanahalli, Bengaluru, Karnataka 562110",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    pincode: 562110,
    lat: 13.2489449600997,
    lng: 77.613665445905,

    gatedCommunity: true,

    constructionStatus: "RTMI",
    bookingPricing: {
      expectedPrice1: 10200000,
    },
    registration: false,
    saleDeed: false,
    khata: false,
    ec: false,
    propertyTax: false,
  },
  {
    category: "resale",
    ownerName: "Arun A",
    projectName: "Century Sports village",
    builderName: "Century Real Estate Holdings Pvt Ltd",
    availableFrom: "2014",
    waterSupply: "borewell",
    amenities: {
      cyclingTrack: true,
      yogaDeck: true,
      outdoorGym: true,
      indoorGym: true,
      yogaRoom: true,
      spa: true,
      steamAndSauna: false,
      kidsPool: true,
      swimmingPool: true,
      aerobicsStudio: true,
      badmintonCourt: true,
      basketballCourt: true,
      volleyBallCourt: true,
      squashCourt: false,
      tennisCourt: true,
      cricketPitch: true,
      tableTennis: true,
      boxCricket: false,
      golf: false,
      multipurposeCourt: false,
      billiards: true,
      skatingRink: false,
      playArea: true,
      library: false,
      creche: false,
      danceStudio: false,
      videoGameRoom: false,
      adventureSports: true,
      oat: true,
      miniTheatre: false,
      functionHall: false,
      banquetHall: true,
      cafe: false,
      barbequePit: true,
      parks: true,
      seniorCitizenCorner: true,
      restHouse: false,
      natureTrail: true,
      terraceGarden: false,
      airConditioner: false,
      interCom: true,
      internet: true,
      petPark: true,
      gatedSecurity: true,
      cctv: true,
      fireAlarm: false,
      fireExtinguisher: true,
      waterSprinkler: false,
      entranceLobby: false,
      atm: false,
      businessCenter: false,
      superMarket: false,
      coWorkingSpace: false,
      lift: false,
      laundary: false,
      pharmacy: false,
      salon: false,
      groceryStore: false,
      houseKeeping: true,
      powerBackup: true,

      gasPipeline: false,
      garbageChute: false,
      rainwaterHarvesting: true,
      organicWasteConverter: false,
      solarHeater: false,
      solarLightning: false,

      sewageTreatmentPlant: true,

      visitorParking: true,
    },
    reraNo: "PRM/KA/RERA/1250/303/PR/170918/000844",
    visitorParking: true,
    unitName: "670",
    propertyType: "plot",
    configuration: "plot",
    plotConfiguration: "30x40",
    carpetArea: 1200,
    directionFacing: "east",
    propertyLocation: "Devanahalli",
    propertyAddress: "IVC Rd, Devanahalli, Bengaluru, Karnataka 562110",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    pincode: 562110,
    lat: 13.2269651987593,
    lng: 77.6844830019991,

    gatedCommunity: true,

    constructionStatus: "RTMI",
    bookingPricing: {
      expectedPrice1: 5500000,
    },
    registration: true,
    saleDeed: true,
    khata: true,
    ec: true,
    propertyTax: false,
  },
  {
    category: "resale",
    ownerName: "Arjun Moorthy",
    projectName: "Century Wintersun",
    builderName: "Century Real Estate Holdings Pvt Ltd",
    availableFrom: "2008",
    waterSupply: "borewell",
    amenities: {
      cyclingTrack: true,
      yogaDeck: true,
      outdoorGym: false,
      indoorGym: true,
      yogaRoom: true,
      spa: true,
      steamAndSauna: true,
      kidsPool: true,
      swimmingPool: true,
      aerobicsStudio: true,
      badmintonCourt: true,
      basketballCourt: true,
      volleyBallCourt: false,
      squashCourt: false,
      tennisCourt: true,
      cricketPitch: false,
      tableTennis: true,
      boxCricket: false,
      golf: false,
      multipurposeCourt: false,
      billiards: true,
      skatingRink: false,
      playArea: true,
      library: false,
      creche: false,
      danceStudio: false,
      videoGameRoom: false,
      adventureSports: false,
      oat: true,
      miniTheatre: false,
      functionHall: false,
      banquetHall: true,
      cafe: false,
      barbequePit: true,
      parks: true,
      seniorCitizenCorner: true,
      restHouse: false,
      natureTrail: false,
      terraceGarden: false,
      airConditioner: false,
      interCom: true,
      internet: true,
      petPark: true,
      gatedSecurity: true,
      cctv: true,
      fireAlarm: true,
      fireExtinguisher: true,
      waterSprinkler: true,
      entranceLobby: false,
      atm: false,
      businessCenter: true,
      superMarket: false,
      coWorkingSpace: false,
      lift: false,
      laundary: false,
      pharmacy: false,
      salon: false,
      groceryStore: false,
      houseKeeping: true,
      powerBackup: true,

      gasPipeline: false,
      garbageChute: false,
      rainwaterHarvesting: true,
      organicWasteConverter: false,
      solarHeater: false,
      solarLightning: false,

      sewageTreatmentPlant: true,

      visitorParking: true,
    },
    unitName: "131",
    propertyType: "villa",
    configuration: "3BHK",
    sba: 8561,
    directionFacing: "north",
    floor: "G+1",
    parking: true,
    parkingType: "covered",
    noOfParking: 2,
    towerName: "A",
    propertyLocation: "Doddaballapura Road",
    propertyAddress:
      "government school, Survey #51,52, Marasandra, kadathanamale Village Hesaraghatta, Hobli, opposite to PKB, Bengaluru, Karnataka 560064",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    pincode: 560064,
    lat: 13.2296241637504,
    lng: 77.5537576017157,
    gatedCommunity: true,
    constructionStatus: "RTMI",
    bookingPricing: {
      expectedPrice1: 33000000,
    },
    registration: true,
    saleDeed: true,
    khata: true,
    ec: true,
    propertyTax: false,
  },
  {
    category: "rental",
    ownerName: "MRS.PADMA VISVANATHAN & MR.RAJAGOPAN PARTHASARTHY",
    projectName: "Century Ethos",
    builderName: "Century Real Estate Holdings Pvt Ltd",
    availableFrom: "2013",
    waterSupply: "borewell",
    amenities: {
      cyclingTrack: true,
      yogaDeck: true,
      outdoorGym: true,
      indoorGym: true,
      yogaRoom: true,
      spa: true,
      steamAndSauna: true,
      kidsPool: true,
      swimmingPool: true,
      aerobicsStudio: true,
      badmintonCourt: false,
      basketballCourt: true,
      volleyBallCourt: false,
      squashCourt: true,
      tennisCourt: true,
      cricketPitch: false,
      tableTennis: true,
      boxCricket: true,
      golf: true,
      multipurposeCourt: true,
      billiards: true,
      skatingRink: false,
      playArea: true,
      library: true,
      creche: true,
      danceStudio: false,
      videoGameRoom: true,
      adventureSports: false,
      oat: true,
      miniTheatre: true,
      functionHall: true,
      banquetHall: true,
      cafe: true,
      barbequePit: true,
      parks: true,
      seniorCitizenCorner: true,
      restHouse: true,
      natureTrail: false,
      terraceGarden: false,
      airConditioner: false,
      interCom: true,
      internet: true,
      petPark: true,
      gatedSecurity: true,
      cctv: true,
      fireAlarm: true,
      fireExtinguisher: true,
      waterSprinkler: true,
      entranceLobby: true,
      atm: true,
      businessCenter: true,
      superMarket: true,
      coWorkingSpace: true,
      lift: true,
      laundary: true,
      pharmacy: false,
      salon: true,
      groceryStore: true,
      houseKeeping: true,
      powerBackup: true,

      gasPipeline: true,
      garbageChute: true,
      rainwaterHarvesting: true,
      organicWasteConverter: false,
      solarHeater: false,
      solarLightning: false,
      carCharging: true,
      sewageTreatmentPlant: true,

      visitorParking: true,
    },
    unitName: "A-1202",
    propertyType: "apartment",
    configuration: "3BHK",
    sba: 3125,
    directionFacing: "north",
    floor: "12",
    parking: true,
    parkingType: "covered",
    noOfParking: 2,
    propertyLocation: "Hebbal",
    propertyAddress:
      "Bellary Rd, opposite Sahakaranagar, Kashi Nagar, Byatarayanapura, Bengaluru, Karnataka 560092",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    pincode: 560092,
    lat: 13.0633483898987,
    lng: 77.5950281309647,
    furnishingType: "none",
    noOfBathrooms: 5,
    gatedCommunity: true,
    propertyAge: "<1 year",
    constructionStatus: "RTMI",
    tenancyStatus: "vaccant",
    siteInspectionStatus: "completed",
    bookingPricing: {
      deposit: 1210000,
      monthlyRental: 110000,
      maintenanceCharges2: 15000,
    },
  },
  {
    category: "rental",
    ownerName: "Vivek AGarwal",
    projectName: "Century Breeze",
    builderName: "Century Real Estate Holdings Pvt Ltd",
    availableFrom: "2013",
    waterSupply: "borewell",
    amenities: {
      cyclingTrack: true,
      yogaDeck: true,
      outdoorGym: false,
      indoorGym: true,
      yogaRoom: false,
      spa: false,
      steamAndSauna: false,
      kidsPool: true,
      swimmingPool: true,
      aerobicsStudio: true,
      badmintonCourt: true,
      basketballCourt: true,
      volleyBallCourt: false,
      squashCourt: true,
      tennisCourt: true,
      cricketPitch: false,
      tableTennis: true,
      boxCricket: false,
      golf: false,
      multipurposeCourt: true,
      billiards: true,
      skatingRink: false,
      playArea: true,
      library: true,
      creche: true,
      danceStudio: false,
      videoGameRoom: false,
      adventureSports: false,
      oat: true,
      miniTheatre: false,
      functionHall: false,
      banquetHall: true,
      cafe: false,
      barbequePit: true,
      parks: true,
      seniorCitizenCorner: true,
      restHouse: false,
      natureTrail: false,
      terraceGarden: false,
      airConditioner: false,
      interCom: true,
      internet: true,
      petPark: true,
      gatedSecurity: true,
      cctv: true,
      fireAlarm: true,
      fireExtinguisher: true,
      waterSprinkler: true,
      entranceLobby: true,
      atm: false,
      businessCenter: true,
      superMarket: false,
      coWorkingSpace: true,
      lift: true,
      laundary: false,
      pharmacy: false,
      salon: false,
      groceryStore: false,
      houseKeeping: true,
      powerBackup: true,

      gasPipeline: false,
      garbageChute: false,
      rainwaterHarvesting: true,
      organicWasteConverter: false,
      solarHeater: false,
      solarLightning: false,

      sewageTreatmentPlant: true,

      visitorParking: true,
    },
    unitName: "A-004",
    propertyType: "apartment",
    configuration: "3BHK",
    sba: 1816,
    directionFacing: "east",
    floor: "ground",
    parking: true,
    parkingType: "covered",
    noOfParking: 2,
    propertyLocation: "Jakkur",
    propertyAddress: "Jakkur Rd, Nehru Nagar, Bengaluru, Karnataka 560064",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    pincode: 560064,
    lat: 13.0960114761995,
    lng: 77.6009207452942,
    furnishingType: "semi",
    noOfBathrooms: 2,
    gatedCommunity: true,
    propertyAge: "<1 year",
    constructionStatus: "RTMI",
    tenancyStatus: "immediate",
    siteInspectionStatus: "completed",
    bookingPricing: {
      deposit: 300000,
      monthlyRental: 30000,
      maintenanceCharges2: 4540,
    },
  },
  {
    category: "rental",
    ownerName: "Krishnan",
    projectName: "Century Breeze",
    builderName: "Century Real Estate Holdings Pvt Ltd",
    availableFrom: "2013",
    waterSupply: "borewell",
    amenities: {
      cyclingTrack: true,
      yogaDeck: true,
      outdoorGym: false,
      indoorGym: true,
      yogaRoom: false,
      spa: false,
      steamAndSauna: false,
      kidsPool: true,
      swimmingPool: true,
      aerobicsStudio: true,
      badmintonCourt: true,
      basketballCourt: true,
      volleyBallCourt: false,
      squashCourt: true,
      tennisCourt: true,
      cricketPitch: false,
      tableTennis: true,
      boxCricket: false,
      golf: false,
      multipurposeCourt: true,
      billiards: true,
      skatingRink: false,
      playArea: true,
      library: true,
      creche: true,
      danceStudio: false,
      videoGameRoom: false,
      adventureSports: false,
      oat: true,
      miniTheatre: false,
      functionHall: false,
      banquetHall: true,
      cafe: false,
      barbequePit: true,
      parks: true,
      seniorCitizenCorner: true,
      restHouse: false,
      natureTrail: false,
      terraceGarden: false,
      airConditioner: false,
      interCom: true,
      internet: true,
      petPark: true,
      gatedSecurity: true,
      cctv: true,
      fireAlarm: true,
      fireExtinguisher: true,
      waterSprinkler: true,
      entranceLobby: true,
      atm: false,
      businessCenter: true,
      superMarket: false,
      coWorkingSpace: true,
      lift: true,
      laundary: false,
      pharmacy: false,
      salon: false,
      groceryStore: false,
      houseKeeping: true,
      powerBackup: true,

      gasPipeline: false,
      garbageChute: false,
      rainwaterHarvesting: true,
      organicWasteConverter: false,
      solarHeater: false,
      solarLightning: false,

      sewageTreatmentPlant: true,

      visitorParking: true,
    },
    unitName: "A-305",
    propertyType: "apartment",
    configuration: "3BHK",
    plotConfiguration: "",
    sba: 1483,
    directionFacing: "west",
    floor: "3",
    parking: true,
    parkingType: "covered",
    noOfParking: 1,
    propertyLocation: "Jakkur",
    propertyAddress: "Jakkur Rd, Nehru Nagar, Bengaluru, Karnataka 560064",
    city: "Bengaluru",
    state: "Karnataka",
    country: "India",
    pincode: 560064,
    lat: 13.0960114761995,
    lng: 77.6009207452942,
    furnishingType: "semi",
    noOfBathrooms: 2,
    gatedCommunity: true,
    propertyAge: "<1 year",
    constructionStatus: "RTMI",
    tenancyStatus: "immediate",
    siteInspectionStatus: "completed",
    bookingPricing: {
      deposit: 270000,
      monthlyRental: 27000,
      maintenanceCharges2: 4540,
    },
  },
];
